[project]
name = "adaptive-learning-system"
description = "AI-powered Adaptive Learning System on Stacks - Phase 2"
authors = ["Your Name <your.email@example.com>"]
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]
costs_version = 2

[contracts.adaptive-learning]
path = "contracts/adaptive-learning.clar"
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[repl.analysis.pass_1]
name = "check_checker"
trusted_sender = false
trusted_caller = false
callee_filter = false

[test.phases]
check = true
coverage = true
unit = true

[test]
coverage_report = true
cost_reporter = "default"
trace = false
cache = false

[[test.coverage_reports]]
type = "lcov"
directory = "coverage"

[development]
node_url = "http://localhost:20443"
miner_url = "http://localhost:20443"
