[project]
name = "adaptive-learning-system"
description = "AI-powered Adaptive Learning System on Stacks"
authors = ["Your Name <your.email@example.com>"]
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2

[contracts.adaptive-learning]
path = "contracts/adaptive-learning.clar"
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
